import 'bootstrap/dist/css/bootstrap.min.css';
import { SearchProvider } from '..//context/searchContext';
import Navbar from '../component/Navbar';
import { AuthProvider } from '../context/authContext';
import Footer from '../component/Footer';
import './style.css';
import { Geist, Geist_Mono } from 'next/font/google';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className='mt-20'>
        <SearchProvider>
          <AuthProvider>
            <Navbar />
            {children}
            <Footer />
          </AuthProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
