
import { SearchProvider } from "@/searchContext"; 
import Navbar from "@/component/Navbar"; 
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <SearchProvider>  
    <html>
      <body>
      <Navbar />
      {children}
      </body>
    </html>
    </SearchProvider>
  );
}
