export const formFields = [
  {
    column: "6",
    type: "text",
    id: "firstName",
    name: "firstName",
    placeholder: "First Name",
  },
  {
    column: "6",
    type: "text",
    id: "lastName",
    name: "lastName",
    placeholder: "Last Name",
  },
  {
    column: "6",
    type: "email",
    id: "email",
    name: "email",
    placeholder: "Email",
  },
  {
    column: "6",
    type: "text",
    id: "phone",
    name: "phone",
    placeholder: "Phone",
  },
  {
    column: "6",
    type: "text",
    id: "country",
    name: "country",
    placeholder: "Country",
    options: [
      {value: "", label: "Select country"},
      {value: "TR", label: "Turkey"},
      {value: "US", label: "United States"},
      {value: "DE", label: "Germany"},
      {value: "FR", label: "France"},
    ],
  },
  {
    column: "6",
    type: "text",
    id: "city",
    name: "city",
    placeholder: "City",
  },
  {
    column: "12",
    type: "text",
    id: "address",
    name: "address",
    placeholder: "Address",
  },
  {
    column: "12",
    type: "text",
    id: "desiredPosition",
    name: "desiredPosition",
    placeholder: "Desired position",
  },
  {
    column: "12",
    type: "text",
    id: "additionalInfo",
    name: "additionalInfo",
    placeholder: "Additional info",
  },
  {
    column: "12",
    type: "file",
    id: "cv",
    name: "cv",
    placeholder: "Add your CV",
    accept: ".pdf, .doc, .docx",
  },
];
