export const formFields = [
  {
    column: '6',
    type: 'text',
    id: 'firstName',
    name: 'firstName',
    placeholder: 'First Name',
  },
  {
    column: '6',
    type: 'text',
    id: 'lastName',
    name: 'lastName',
    placeholder: 'Last Name',
  },
  {
    column: '6',
    type: 'email',
    id: 'email',
    name: 'email',
    placeholder: 'Email',
  },
  {
    column: '6',
    type: 'text',
    id: 'phone',
    name: 'phone',
    placeholder: 'Phone',
  },
  {
    column: '6',
    type: 'select',
    id: 'country',
    name: 'country',
    placeholder: 'Country',
    options: [
      { value: '', label: 'Country' },
      { value: 'TR', label: 'Turkey' },
      { value: 'US', label: 'United States' },
      { value: 'DE', label: 'Germany' },
      { value: 'FR', label: 'France' },
    ],
  },
  {
    column: '6',
    type: 'text',
    id: 'city',
    name: 'city',
    placeholder: 'City',
  },
  {
    column: '12',
    type: 'text',
    id: 'address',
    name: 'address',
    placeholder: 'Address',
  },
  {
    column: '12',
    type: 'select',
    id: 'desiredPosition',
    name: 'desiredPosition',
    placeholder: 'Desired position',
    options: [
      { value: '', label: 'Position' },
      { value: 'tech', label: 'Tech' },
      { value: 'marketing', label: 'Marketing' },
      { value: 'hr', label: 'HR' },
      { value: 'support', label: 'Support' },
      { value: 'management', label: 'Managment' },
    ],
  },
  {
    column: '12',
    type: 'textarea',
    id: 'additionalInfo',
    name: 'additionalInfo',
    placeholder: 'Additional info',
    rows: 3,
    cols: 50,
  },
  {
    column: '12',
    type: 'file',
    id: 'cv',
    name: 'cv',
    placeholder: 'Add your CV',
    accept: '.pdf, .doc, .docx',
  },
];
