export const movieTypeMap = {
  1: "Bilim Kurgu",
  2: "Dram",
  3: "Aksiyon",
  4: "Komedi",
  5: "Korku",
  6: "Gerilim",
  7: "Romantik",
  8: "Animasyon",
  9: "Fantastik",
  10: "Belgesel",
  11: "Macera",
  12: "Suç",
  13: "Müzikal",
  14: "Gizem",
  15: "Western",
  16: "Savaş",
  17: "Spor",
  18: "Aile",
  19: "Biyografi",
  20: "Tarih",
  21: "Festival",
};
