import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";

import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Navbar from '../components/Navbar';
import Footer from "@/components/Footer";
import AuthProvider from "@/providers/authProvider";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={dmSans.variable} >

      <body >
        <AuthProvider>
          <Navbar />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
