import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import AddBootstrap from "./AddBootstrap";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/all.min.css" precedence="default" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AddBootstrap />
        {children}
        <script src="https://kit.fontawesome.com/0460a9927e.js" crossOrigin="anonymous"></script>
      </body>
    </html>
  );
}
