export default {
  en: {
    "Buy & Sell Digital Assets In The Rocket": "Buy & Sell Digital Assets In The Rocket",
    "Coin rocket is the easiest, safest, and fastest way to buy & sell crypto asset exchange": "Coin rocket is the easiest, safest, and fastest way to buy & sell crypto asset exchange.",
    "Get started now": "Get started now",
    "Our Partners": "Our Partners",
    "Crypto": "Crypto",
    "Market Update": "Market Update",
    "Hot": "Hot",
    "New": "New",
    "How It Work": "How It Work",
    "Stacks is a production-ready library of stackable content blocks built in React Native": "Stacks is a production-ready library of stackable content blocks built in React Native.",
    "STEP 1": "STEP 1",
    "STEP 2": "STEP 2",
    "STEP 3": "STEP 3",
    "STEP 4": "STEP 4",
    "Download": "Download",
    "Connect Wallet": "Connect Wallet",
    "Start Trading": "Start Trading",
    "Earn Money": "Earn Money",
    "What Is Rockie": "What Is Rockie",
    "experience_variety_of_trading_on_bitcoast": "Bitcoast'ta çeşitli ticaret türlerini deneyimleyin. Spot Ticaret, Vadeli İşlemler, P2P, Stake Etme, Madencilik ve Marjin gibi işlemleri kullanabilirsiniz.",
    "View real-time cryptocurrency prices": "View real-time cryptocurrency prices",
    "buy_and_sell_BTC": "Buy and sell BTC, ETH, XRP, OKB, Etc...",
    "Explore More": "Explore More",
    "Free Your Money & Invest": "Free Your Money & Invest",
    "With Confident": "With Confident",
    "With Cryptor Trade, you can be sure your trading skills are matched": "With Cryptor Trade, you can be sure your trading skills are matched",
    "Buy, Sell, And Trade On The Go": "Buy, Sell, And Trade On The Go",
    "Manage your holdings from your mobile device": "Manage your holdings from your mobile device",
    "Take Control Of Your Wealth": "Take Control Of Your Wealth",
    "Rest assured you (and only you) have access to your funds": "Rest assured you (and only you) have access to your funds",
    "Our Customers Love": "Our Customers Love",
    "What We Do": "What We Do",
    "Transform Your Ideas Into Reality With Finsweet": "Transform Your Ideas Into Reality With Finsweet",
    "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    "Customer Reviews": "Customer Reviews",
    "great_course_i_really": "Great course I really enjoyed it and the course was way easy to learn with very good explanations of the code, I could easily understand and develop applications with the knowledge gathered during the course.",
    "Director, Company": "Director, Company",
    "Earn up to $25 worth of crypto": "Earn up to $25 worth of crypto",
    "Discover How Specific Cryptocurrencies Work — And Get A Bit Of Each Crypto To Try Out For Yourself": "Discover How Specific Cryptocurrencies Work — And Get A Bit Of Each Crypto To Try Out For Yourself.",
    "See All Coins": "See All Coins",
    "Name": "Name",
    "Last Price": "Last Price",
    "24h %": "24h %",
    "Market Cap": "Market Cap",
    "Last 7 Days": "Last 7 Days",
    "Search Coin": "Search Coin",
    "Trade": "Trade",
    "Create Account": "Create Account",
    "Today’s Crypto currency prices": "Today’s Crypto currency prices",
    "the_global_crypto": "The global crypto market cap is $1.86T",
    "Favorites": "Favorites",
    "Derivatives": "Derivatives",
    "Spot": "Spot",
    "All": "All",
    "Inverse Perpetual": "Inverse Perpetual",
    "USDT Perpetual": "USDT Perpetual",
    "Inserve Futures": "Inserve Futures",
    "Learn And Earn": "Learn And Earn",
    "Stacks is a production_ready library of stackable content blocks built in React Native": "Stacks is a production-ready library of stackable content blocks built in React Native.",
    "Learn & Earn": "Learn & Earn",
    "Learn about U18 coin and earn an All_Access Pass": "Learn about U18 coin and earn an All-Access Pass",
    "Feb 03, 2021": "Feb 03, 2021",
    "Lets talk": "Let’s talk! 👋",
    "phone_number": "+98 902 353 2926",
    "email_sina_hoseini379_gmail_com": "sina.hoseini379@gmail.com",
    "Copyright_2023_Free_For_Earths_People": "Copyright © 2023 Free For Earth's People",
    "Products": "Products",
    "Exchange": "Exchange",
    "Launchpad": "Launchpad",
    "Binance Pay": "Binance Pay",
    "Services": "Services",
    "Buy Crypto": "Buy Crypto",
    "Markets": "Markets",
    "Trading Fee": "Trading Fee",
    "Affiliate Program": "Affiliate Program",
    "Referral Program": "Referral Program",
    "API": "API",
    "Support": "Support",
    "Bybit Learn": "Bybit Learn",
    "Help Center": "Help Center",
    "User Feedback": "User Feedback",
    "Submit a Request": "Submit a Request",
    "API Documentation": "API Documentation",
    "Trading Rules": "Trading Rules",
    "About Us": "About Us",
    "About Bybit": "About Bybit",
    "Authenticity Check": "Authenticity Check",
    "Careers": "Careers",
    "Business Contacts": "Business Contacts",
    "Blog": "Blog",
    "Load more": "Load More",
    "Home": "Home",
    "Market": "Market",
    "ByFi Center": "ByFi Center",
    "More": "More",
    "Asset": "Asset",
    "Order & Trades": "Order & Trades",
    "Wallet": "Wallet",
    "Dropdown": "Dropdown",
    "Trading Market": "Trading Market",
    "Buy": "Buy",
    "Sell": "Sell",
    "Pay": "Pay",
    "Receive": "Receive",
    "Limit": "Limit",
    "Stop limit": "Stop limit",
    "Stop market": "Stop market",
    "Select Amount": "Select Amount",
    "Processing": "Processing...",
    "Order History": "Order History",
    "Open Orders": "Open Orders",
    "Closed Orders": "Closed Orders",
    "Search By Date": "Search By Date",
    "Date": "Date",
    "Pair": "Pair",
    "Buy/Sell": "Buy/Sell",
    "Price": "Price",
    "Executed": "Executed",
    "Total": "Total"
  },
  tr: {
    "Buy & Sell Digital Assets In The Rocket": "Dijital Varlıkları Roket ile Al & Sat",
    "Coin rocket is the easiest, safest, and fastest way to buy & sell crypto asset exchange": "Coin Rocket, kripto varlık alım satımı için en kolay, güvenli ve hızlı yoldur.",
    "Get started now": "Hemen başla",
    "Our Partners": "Ortaklarımız",
    "Crypto": "Kripto",
    "Market Update": "Piyasa Güncellemesi",
    "Hot": "Popüler",
    "New": "Yeni",
    "How It Work": "Nasıl Çalışır",
    "Stacks is a production-ready library of stackable content blocks built in React Native": "Stacks, React Native ile oluşturulmuş hazır kullanılabilir içerik blokları kütüphanesidir.",
    "STEP 1": "ADIM 1",
    "STEP 2": "ADIM 2",
    "STEP 3": "ADIM 3",
    "STEP 4": "ADIM 4",
    "Download": "İndir",
    "Connect Wallet": "Cüzdan Bağla",
    "Start Trading": "Alım Satıma Başla",
    "Earn Money": "Para Kazan",
    "What Is Rockie": "Rockie Nedir",
    "experience_variety_of_trading_on_bitcoast": "Bitcoast'ta çeşitli ticaret türlerini deneyimleyin. Spot Ticaret, Vadeli İşlemler, P2P, Stake Etme, Madencilik ve Marjin gibi işlemleri kullanabilirsiniz.",
    "View real-time cryptocurrency prices": "Gerçek zamanlı kripto para fiyatlarını görüntüleyin",
    "buy_and_sell_BTC": "BTC, ETH, XRP, OKB ve daha fazlasını alıp satın...",
    "Explore More": "Daha Fazlasını Keşfet",
    "Free Your Money & Invest": "Paranı Özgürleştir ve Yatırım Yap",
    "With Confident": "Güvenle",
    "With Cryptor Trade, you can be sure your trading skills are matched": "Cryptor Trade ile, alım satım becerilerinizin karşılık bulduğundan emin olabilirsiniz",
    "Buy, Sell, And Trade On The Go": "Yolda Al, Sat ve Ticaret Yap",
    "Manage your holdings from your mobile device": "Varlıklarını mobil cihazınla yönet",
    "Take Control Of Your Wealth": "Varlıkların Üzerinde Kontrol Sağla",
    "Rest assured you (and only you) have access to your funds": "Fonlarınıza sadece senin erişimin olduğundan emin ol",
    "Our Customers Love": "Müşterilerimiz Seviyor",
    "What We Do": "Yaptığımız Şeyleri",
    "Transform Your Ideas Into Reality With Finsweet": "Fikirlerini Finsweet ile Gerçeğe Dönüştür",
    "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout": "Bir okuyucunun bir sayfanın düzenine bakarken dikkatinin okunabilir içerikten dağıldığı bilinen bir gerçektir.",
    "Customer Reviews": "Müşteri Yorumları",
    "great_course_i_really": "Harika bir kurs, gerçekten keyif aldım. Kodların çok iyi açıklanması sayesinde kolayca öğrendim ve uygulamalar geliştirebildim.",
    "Director, Company": "Yönetici, Şirket",
    "Earn up to $25 worth of crypto": "25$'a kadar kripto kazan",
    "Discover How Specific Cryptocurrencies Work — And Get A Bit Of Each Crypto To Try Out For Yourself": "Belirli kripto paraların nasıl çalıştığını keşfet — ve her birinden denemek için biraz kazan.",
    "See All Coins": "Tüm Paraları Gör",
    "Name": "İsim",
    "Last Price": "Son Fiyat",
    "24h %": "24s %",
    "Market Cap": "Piyasa Değeri",
    "Last 7 Days": "Son 7 Gün",
    "Search Coin": "Coin Ara",
    "Trade": "Al Sat",
    "Create Account": "Hesap Oluştur",
    "Today’s Crypto currency prices": "Bugünün Kripto Para Fiyatları",
    "the_global_crypto": "Küresel kripto piyasa değeri $1.86T",
    "Favorites": "Favoriler",
    "Derivatives": "Türevler",
    "Spot": "Spot",
    "All": "Hepsi",
    "Inverse Perpetual": "Ters Süresiz",
    "USDT Perpetual": "USDT Süresiz",
    "Inserve Futures": "Ters Vadeli",
    "Learn And Earn": "Öğren ve Kazan",
    "Stacks is a production_ready library of stackable content blocks built in React Native": "Stacks, React Native ile hazırlanmış istiflenebilir içerik bloklarından oluşan üretime hazır bir kütüphanedir.",
    "Learn & Earn": "Öğren & Kazan",
    "Learn about U18 coin and earn an All_Access Pass": "U18 coin hakkında bilgi edin ve Tüm Erişim Kartı kazanın",
    "Feb 03, 2021": "03 Şubat 2021",
    "Lets talk": "Haydi konuşalım! 👋",
    "phone_number": "+98 902 353 2926",
    "email_sina_hoseini379_gmail_com": "sina.hoseini379@gmail.com",
    "Copyright_2023_Free_For_Earths_People": "Telif Hakkı © 2023 Dünyanın İnsanları İçin Ücretsiz",
    "Products": "Ürünler",
    "Exchange": "Borsa",
    "Launchpad": "Lansman Platformu",
    "Binance Pay": "Binance Pay",
    "Services": "Hizmetler",
    "Buy Crypto": "Kripto Satın Al",
    "Markets": "Piyasalar",
    "Trading Fee": "İşlem Ücreti",
    "Affiliate Program": "Ortaklık Programı",
    "Referral Program": "Referans Programı",
    "API": "API",
    "Support": "Destek",
    "Bybit Learn": "Bybit Öğren",
    "Help Center": "Yardım Merkezi",
    "User Feedback": "Kullanıcı Geri Bildirimi",
    "Submit a Request": "Talep Gönder",
    "API Documentation": "API Dökümantasyonu",
    "Trading Rules": "Ticaret Kuralları",
    "About Us": "Hakkımızda",
    "About Bybit": "Bybit Hakkında",
    "Authenticity Check": "Orijinallik Kontrolü",
    "Careers": "Kariyer",
    "Business Contacts": "İş İletişimleri",
    "Blog": "Blog",
    "Load more": "Daha fazla yükle",
    "Home": "Ana Sayfa",
    "Market": "Piyasa",
    "ByFi Center": "ByFi Merkezi",
    "More": "Daha Fazla",
    "Asset": "Varlık",
    "Order & Trades": "Emirler ve İşlemler",
    "Wallet": "Cüzdan",
    "Dropdown": "Açılır Menü",
    "Trading Market": "Ticaret Pazarı",
    "Buy": "Satın Al",
    "Sell": "Sat",
    "Pay": "Öde",
    "Receive": "Al",
    "Limit": "Limit",
    "Stop limit": "Durdurma limiti",
    "Stop market": "Piyasa durdurma",
    "Select Amount": "Miktar Seç",
    "Processing": "İşleniyor...",
    "Order History": "Sipariş Geçmişi",
    "Open Orders": "Açık Emirler",
    "Closed Orders": "Kapalı Emirler",
    "Search By Date": "Tarihe Göre Ara",
    "Date": "Tarih",
    "Pair": "Parite",
    "Buy/Sell": "Al/Sat",
    "Price": "Fiyat",
    "Executed": "Gerçekleşen",
    "Total": "Toplam"
  },
}