import { ThemeProvider } from "@/app/context/ThemeContext"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return ( <ThemeProvider>
                {children}
              </ThemeProvider>
  )
}
