import { SearchProvider } from '@/context/searchContext';
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from '@/component/Navbar';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/context/authContext';
import 'bootstrap/dist/css/bootstrap.min.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <SearchProvider>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
