export const UNIVERSITIES = [
  "Abant İzzet Baysal Üniversitesi",
  "Abdullah Gül Üniversitesi",
  "Acıbadem Üniversitesi",
  "Adana Bilim ve Teknoloji Üniversitesi",
  "Adnan Menderes Üniversitesi",
  "Adıyaman Üniversitesi",
  "Afyon Kocatepe Üniversitesi",
  "Ahi Evran Üniversitesi",
  "Akdeniz Üniversitesi",
  "Akev Üniversitesi",
  "Aksaray Üniversitesi",
  "Alanya Alaaddin Keykubat Üniversitesi",
  "Alanya Hamdullah Emin Paşa Üniversitesi",
  "Amasya Üniversitesi",
  "Anadolu Üniversitesi",
  "Anka Teknoloji Üniversitesi",
  "Ankara Sosyal Bilimler Üniversitesi",
  "Ankara Üniversitesi",
  "Ardahan Üniversitesi",
  "Artvin Çoruh Üniversitesi",
  "Atatürk Üniversitesi",
  "Atılım Üniversitesi",
  "Avrasya Üniversitesi",
  "Ağrı İbrahim Çeçen Üniversitesi",
  "Bahçeşehir Üniversitesi",
  "Balıkesir Üniversitesi",
  "Bandırma Onyedi Eylül Üniversitesi",
  "Bartın Üniversitesi",
  "Batman Üniversitesi",
  "Bayburt Üniversitesi",
  "Başkent Üniversitesi",
  "Beykent Üniversitesi",
  "Bezmiâlem Vakıf Üniversitesi",
  "Bilecik Şeyh Edebali Üniversitesi",
  "Bilkent Üniversitesi",
  "Bingöl Üniversitesi",
  "Biruni Üniversitesi",
  "Bitlis Eren Üniversitesi",
  "Bozok Üniversitesi",
  "Boğaziçi Üniversitesi",
  "Bursa Orhangazi Üniversitesi",
  "Bursa Teknik Üniversitesi",
  "Bülent Ecevit Üniversitesi",
  "Canik Başarı Üniversitesi",
  "Celal Bayar Üniversitesi",
  "Cumhuriyet Üniversitesi",
  "Çanakkale Onsekiz Mart Üniversitesi",
  "Çankaya Üniversitesi",
  "Çankırı Karatekin Üniversitesi",
  "Çağ Üniversitesi",
  "Çukurova Üniversitesi",
  "Deniz Harp Okulu",
  "Dicle Üniversitesi",
  "Dokuz Eylül Üniversitesi",
  "Doğuş Üniversitesi",
  "Dumlupınar Üniversitesi",
  "Düzce Üniversitesi",
  "Ege Üniversitesi",
  "Erciyes Üniversitesi",
  "Erzincan Üniversitesi",
  "Erzurum Teknik Üniversitesi",
  "Eskişehir Osmangazi Üniversitesi",
  "Fatih Sultan Mehmet Üniversitesi",
  "Fatih Üniversitesi",
  "Fırat Üniversitesi",
  "Galatasaray Üniversitesi",
  "Gazi Üniversitesi",
  "Gaziantep Üniversitesi",
  "Gaziosmanpaşa Üniversitesi",
  "Gebze Teknik Üniversitesi",
  "Gedik Üniversitesi",
  "Gediz Üniversitesi",
  "Giresun Üniversitesi",
  "Gülhane Askeri Tıp Akademisi",
  "Gümüşhane Üniversitesi",
  "Hacettepe Üniversitesi",
  "Hakkari Üniversitesi",
  "Haliç Üniversitesi",
  "Harran Üniversitesi",
  "Hasan Kalyoncu Üniversitesi",
  "Hava Harp Okulu",
  "Hitit Üniversitesi",
  "Iğdır Üniversitesi",
  "Işık Üniversitesi",
  "Kadir Has Üniversitesi",
  "Kafkas Üniversitesi",
  "Kahramanmaraş Sütçü İmam Üniversitesi",
  "Kanuni Üniversitesi",
  "Kara Harp Okulu",
  "Karabük Üniversitesi",
  "Karadeniz Teknik Üniversitesi",
  "Karamanoğlu Mehmetbey Üniversitesi",
  "Karatay Üniversitesi",
  "Kastamonu Üniversitesi",
  "Kilis 7 Aralık Üniversitesi",
  "Kocaeli Üniversitesi",
  "Konya Gıda Tarım Üniversitesi",
  "Koç Üniversitesi",
  "Kırklareli Üniversitesi",
  "Kırıkkale Üniversitesi",
  "MEF Üniversitesi",
  "Maltepe Üniversitesi",
  "Mardin Artuklu Üniversitesi",
  "Marmara Üniversitesi",
  "Mersin Üniversitesi",
  "Mevlana Üniversitesi",
  "Munzur Üniversitesi",
  "Muğla Sıtkı Koçman Üniversitesi",
  "Mustafa Kemal Üniversitesi",
  "Namık Kemal Üniversitesi",
  "Necmettin Erbakan Üniversitesi",
  "Nevşehir Hacı Bektaş Veli Üniversitesi",
  "Niğde Ömer Halisdemir Üniversitesi",
  "Ondokuz Mayıs Üniversitesi",
  "Ordu Üniversitesi",
  "Orta Doğu Teknik Üniversitesi",
  "Osmaniye Korkut Ata Üniversitesi",
  "Pamukkale Üniversitesi",
  "Piri Reis Üniversitesi",
  "Recep Tayyip Erdoğan Üniversitesi",
  "Sabancı Üniversitesi",
  "Sakarya Üniversitesi",
  "Samsun Üniversitesi",
  "Selçuk Üniversitesi",
  "Sinop Üniversitesi",
  "Süleyman Demirel Üniversitesi",
  "Şırnak Üniversitesi",
  "Trakya Üniversitesi",
  "Tobb Ekonomi ve Teknoloji Üniversitesi",
  "Toros Üniversitesi",
  "Ufuk Üniversitesi",
  "Uludağ Üniversitesi",
  "Uşak Üniversitesi",
  "Van Yüzüncü Yıl Üniversitesi",
  "Yaşar Üniversitesi",
  "Yeditepe Üniversitesi",
  "Yıldırım Beyazıt Üniversitesi",
  "Yıldız Teknik Üniversitesi",
  "Yüksek İhtisas Üniversitesi",
];
export const LANGUAGES = [
  "İngilizce",
  "Fransızca",
  "Almanca",
  "İspanyolca",
  "Rusça",
  "Arapça",
  "Çince",
  "Japonca",
];
export const levels = [
  "Beginner",
  "Intermediate",
  "Advanced",
];
