import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.scss";
import Head from "./components/Templates/Header/Head";
import Footer from "./components/Templates/Footer/Footer";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={dmSans.variable}>
        <ThemeProvider enableSystem={false} attribute="data-theme">
          <Head />
          <main>{children}</main>
          <Footer></Footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
