import "./globals.css";
import Footer from "./Templates/Footer";
import Header from "./Templates/Header";
import SideBar from "./Templates/SideBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased font-sans`}>
        <div className="flex">
          <div>
            <SideBar />
          </div>
          <div className="flex-1 flex flex-col">
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
