import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import SiteFooter from "../components/site-footer";
import SiteNavbar from "../components/site-navbar";
import AddBootstrap from "./AddBootstrap";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AddBootstrap />
        <SiteNavbar />
        {children}
        <SiteFooter />
      </body>
    </html>
  );
}
