import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import SiteFooter from "../components/site-footer";
import AddBootstrap from "./AddBootstrap";
import Navbar from "@/components/Navbar/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
        <AddBootstrap />
        <Navbar />
        {children}
        <SiteFooter />
      </body>
    </html>
  );
}
