import type { Metadata } from "next";
import { DM_Sans } from 'next/font/google'
import "./globals.scss";

import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';


const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
  variable: '--font-dm-sans',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body className={dmSans.className}>
        <NextIntlClientProvider >
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
